development:
  adapter: mysql
  database: myousica_development
  socket: /tmp/mysql.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql
  database: myousica_development
  socket: /tmp/mysql.sock