development:
  adapter: mysql
  database: myousica_development
  socket: /opt/local/var/run/mysql5/mysqld.sock
  username: myousica
  password: adelao

test:
  adapter: mysql
  database: myousica_test
  socket: /opt/local/var/run/mysql5/mysqld.sock
  username: myousica
  password: adelao

production:
  adapter: mysql
  database: myousica_production
  socket: /opt/local/var/run/mysql5/mysqld.sock
  username: myousica
  password: adelao
